add homework.py and tests.py
NadiiaKozak/common pull request #1
Opened 2019-09-24 15:58 UTC by NadiiaKozak

2019-09-24 20:35 UTC, yuriimchg requested changes
Привіт :wave: 
Я переглянув завдання і в мене є декілька зауважень до нього.
Крім того, є ще деякі стилістичні зауваження, наприклад, між операторами та змінними має бути пробіл. Для того, щоб усувати такого вигляду проблеми, раджу використати `pylint` - він простий у використанні і бачить всі порушення стандарту PEP-8.

2019-09-24 20:35 UTC, yuriimchg commented on git/homework.py
> +    if first == second :
цю функцію можна зробити простіше - не використовуючи `if / else`.

2019-09-24 20:35 UTC, yuriimchg commented on git/homework.py
> +    if type(first)==type(second):
зауваження аналогічне до попереднього завдання;
+ краще не прирівнювати типи, а використовувати вбудований метод `isinstance(a, b)`

2019-09-24 20:35 UTC, yuriimchg commented on git/homework.py
> -    pass
також можна зробити без `if / else`

2019-09-24 20:35 UTC, yuriimchg commented on git/homework.py
> +    if type(first_value)is not int:
тут також краще використати `isinstance`

2019-09-24 20:35 UTC, yuriimchg commented on git/homework.py
> +    if type(first_value)is not int:
і конструкцію `try / except` замість `if / else`

2019-09-24 20:35 UTC, yuriimchg commented on git/homework.py
> +        mult=first_value1*second_value1
тут можна уникнути зайвого переприсвоєння:
```suggestion
        return first_value1 * second_value1
```

2019-09-24 20:35 UTC, yuriimchg commented on git/homework.py
> +
тут потрібно ще викликати `ValueError` з текстом, який наразі прінтиться, а не просто виводити його

2019-09-24 20:35 UTC, yuriimchg commented on git/homework.py
> +        return True
тут також варто уникнути `if / else`

2019-09-24 20:35 UTC, yuriimchg commented on git/homework.py
> +    alphabetic=list(str('qwertyuiopasdfghjklzxcvbnm'))
у цій функції більш бажано використати вбудовану бібліотеку з символами, ніж вводити їх вручну

2019-09-24 20:35 UTC, yuriimchg commented on git/homework.py
> +    while i<z-1:
Згідно з PEP-8, змінні варто називати більш інформативно.

2019-09-25 10:06 UTC, dimigor commented on git/homework.py
> +
too many blank lines. Follow PEP8, please

2019-09-25 13:50 UTC, NadiiaKozak commented on git/homework.py
> +
Зауваження враховані.

2019-09-25 19:36 UTC, yuriimchg approved these changes
все ок, молодець :+1:

2019-10-02 07:22 UTC, merged