Django1
NadiiaKozak/common pull request #12
Opened 2019-12-27 16:45 UTC by NadiiaKozak

2019-12-30 23:16 UTC, yuriimchg requested changes
переглянув дз - загалом все досить добре, всі умови виконання дз виконані. 
Є деякі дрібні зауваження.
Але також тут є 4 дз з фласку - його не має бути в цьому пул реквесті. Це важливо.

2019-12-30 23:16 UTC, yuriimchg commented on django_practice/django_practice/test.py
> +
імпорти бажано впорядковувати таким чином:
* імпорти зі стандартної бібліотеки
* імпорти з встановлених бібліотек
* імпорти локальних модулів
_+_ між кожною групкою має бути пробіл

https://www.python.org/dev/peps/pep-0008/#imports

2019-12-30 23:16 UTC, yuriimchg commented on django_practice/django_practice/test.py
> +        assert result == actual_result
чому б тут не використати isinstance()?

2019-12-30 23:16 UTC, yuriimchg commented on django_practice/django_practice/urls.py
> +    url(r'^admin/', admin.site.urls),
не впевнений, що лінк буде парситися як регулярний вираз

2019-12-30 23:16 UTC, yuriimchg commented on django_practice/django_practice/views.py
> +POCKEMON_URL = 'https://pokeapi.co/api/v2/'
URL / шляхи бажано виносити в конфіги

2019-12-30 23:16 UTC, yuriimchg commented on flask_4/Rooms/__init__.py
> +api.add_resource(Rooms, "/rooms")
no newline at the end of file

2020-01-01 19:08 UTC, NadiiaKozak commented on django_practice/django_practice/test.py
> +
Дз по фласку з цього бранча видалила. Імпорти впорядкувала (Ctrl+Alt+O)

2020-01-01 20:39 UTC, NadiiaKozak commented on django_practice/django_practice/test.py
> +
Дякую за зауваження! Файли по дз4 Flask видалила.Імпорти впорядкувала (Ctrl+Alt+O)

2020-01-01 20:39 UTC, NadiiaKozak commented on django_practice/django_practice/test.py
> +        assert result == actual_result
застосувала isinstance()

2020-01-01 20:39 UTC, NadiiaKozak commented on django_practice/django_practice/urls.py
> +    url(r'^admin/', admin.site.urls),
перептсала через path()

2020-01-01 20:40 UTC, NadiiaKozak commented on django_practice/django_practice/urls.py
> +    url(r'^admin/', admin.site.urls),
переписала через path()

2020-01-01 20:40 UTC, NadiiaKozak commented on django_practice/django_practice/views.py
> +POCKEMON_URL = 'https://pokeapi.co/api/v2/'
винесла в коремий файл config.py

2020-01-01 20:41 UTC, NadiiaKozak commented on flask_4/Rooms/__init__.py
> +api.add_resource(Rooms, "/rooms")
flask4 видалила з даного pull request

2020-01-02 21:47 UTC, yuriimchg requested changes
виглядає дуже гарно,
є ще трошки зауваження щодо файлика з конфігами і лінтера:
```
./manage.py:14:13: F401 'django' imported but unused
./django_practice/views.py:16:80: E501 line too long (88 > 79 characters)
./django_practice/views.py:23:80: E501 line too long (87 > 79 characters)
./django_practice/views.py:24:33: E127 continuation line over-indented for visual indent
./django_practice/settings.py:89:80: E501 line too long (91 > 79 characters)
./django_practice/settings.py:92:80: E501 line too long (81 > 79 characters)
./django_practice/settings.py:95:80: E501 line too long (82 > 79 characters)
./django_practice/settings.py:98:80: E501 line too long (83 > 79 characters)
./django_practice/test.py:33:13: F841 local variable 'actual_result' is assigned to but never used
./django_practice/test.py:39:1: W391 blank line at end of file
./django_practice/urls.py:16:1: F401 'django.conf.urls.url' imported but unused

```

2020-01-02 21:47 UTC, yuriimchg commented on django_practice/django_practice/config.py
> +    return response.json()
методи якраз не бажано в конфігах зберігати

2020-01-02 21:47 UTC, yuriimchg commented on django_practice/django_practice/config.py
> +    return response.json()
особливо, якщо це get запит

2020-01-02 21:47 UTC, yuriimchg commented on django_practice/django_practice/config.py
> +    return response.json()
_+_ вже є файлик з конфігами - `settings.py` - можна перенести туди POCKEMON_URL, щоб не плодити багато модулів, які використовуються для одного й того самого призначення

2020-01-03 17:04 UTC, yuriimchg approved these changes
все ок :+1: 
вітаю з завершеним дз :fire:

2020-01-06 19:52 UTC, merged