add homework.py to python_functionality
NadiiaKozak/common pull request #3
Opened 2019-10-02 07:24 UTC by NadiiaKozak

2019-10-02 13:58 UTC, dimigor requested changes

2019-10-02 13:58 UTC, dimigor commented on python_functionality/homework.py
> +    for i in range(len(data)):
you can iterate over a list/dict without range

2019-10-02 13:58 UTC, dimigor commented on python_functionality/homework.py
> +        return min(data)
you can simplify this part 
```suggestion
        if data:
```

2019-10-02 13:58 UTC, dimigor commented on python_functionality/homework.py
> +        return None
same as above

2019-10-02 13:58 UTC, dimigor commented on python_functionality/homework.py
> +    L = []
do not name variable with uppercase

2019-10-02 13:58 UTC, dimigor commented on python_functionality/homework.py
> +    return max(L)
try to use list/dict comp

2019-10-03 16:03 UTC, dimigor requested changes

2019-10-03 16:03 UTC, dimigor commented on python_functionality/homework.py
> +    for i in range(len(data)):
python has posibility to iterate over list, and we do not need to use `range` in this case

2019-10-03 18:18 UTC, NadiiaKozak commented on python_functionality/homework.py
> +    for i in range(len(data)):
Дякую за зауваження. Замінила range.

2019-10-04 09:21 UTC, yuriimchg approved these changes
привіт
є деякі зауваження по форматуванню коду

python_functionality/homework.py:32:1: E302 expected 2 blank lines, found 1
python_functionality/homework.py:36:80: E501 line too long (92 > 79 characters)
python_functionality/homework.py:59:1: E303 too many blank lines (3)
python_functionality/homework.py:71:1: E303 too many blank lines (4)

але дз виконане дуже класно
тому апруваю
:+1:

2019-10-04 09:21 UTC, yuriimchg commented on python_functionality/homework.py
> +    return l
:open_mouth:

2019-10-04 09:21 UTC, yuriimchg commented on python_functionality/homework.py
> +    return l
дуже круто

2019-10-04 09:21 UTC, yuriimchg commented on python_functionality/homework.py
> +    return l
але внесу ще свої 5 копійок
```suggestion
    return [{key: (val.title() if key == 'name' else val) for (key, val) in i.items()} for i in data]
```

2019-10-04 09:21 UTC, yuriimchg commented on python_functionality/homework.py
> +    return l
```suggestion
    return [{key: val for (key, val) in i.items() if key not in redundant_keys} for i in data]
```

2019-10-04 09:21 UTC, yuriimchg commented on python_functionality/homework.py
> +    return l
тут також
не потрібно перезаписувати змінні)

2019-10-04 09:21 UTC, yuriimchg commented on python_functionality/homework.py
> +    return (task_3_find_item_via_value(data, min(l))[0])
це найоригінальніше рішення зі всіх, які я бачив

2019-10-04 09:21 UTC, yuriimchg commented on python_functionality/homework.py
> +    sum_characters_positions = sum(list(ord(c) for c in text))
якщо є `sum`, то не обов'язково обгортати генератор списком

2019-10-07 06:56 UTC, merged