add homework.py to oop
NadiiaKozak/common pull request #6
Opened 2019-10-14 15:47 UTC by NadiiaKozak

2019-10-16 07:47 UTC, dimigor requested changes

2019-10-16 07:47 UTC, dimigor commented on oop/homework.py
> +    saturation_level = 50
Are you sure that this variable has to be a class variable?
Read about the difference between class and instance variables

2019-10-16 07:47 UTC, dimigor commented on oop/homework.py
> +            self._increase_saturation_level(2)
to avoid multiple conditions create dict like `{'milk': 2, ...}` and in this method just call `self._increase_saturation_level(dict.get(product, 0))`

2019-10-16 07:47 UTC, dimigor commented on oop/homework.py
> +            return "Your cat is died :("
if a cat has died, you do not need to stop the program?

2019-10-16 07:47 UTC, dimigor commented on oop/homework.py
> +        elif run_km > 200:
just else

2019-10-17 19:57 UTC, yuriimchg approved these changes
+

2019-10-17 19:57 UTC, yuriimchg commented on oop/homework.py
> +from sys import exit
ти імпортуєш exit, але не користуєшся ним
не треба так)

2019-10-17 20:31 UTC, merged