add HW advanced flask
NadiiaKozak/common pull request #9
Opened 2019-11-05 09:26 UTC by NadiiaKozak

2019-11-09 17:08 UTC, dimigor requested changes

2019-11-09 17:08 UTC, dimigor commented on flask_advanced/blueprint/Products/templates/add_product.html
> +       		<form method="post" enctype="multipart/form-data">
bad tabulation, too much tabs

2019-11-09 17:08 UTC, dimigor commented on flask_advanced/blueprint/Products/templates/all_products.html
> +    <img src="{{url_for('product.static', filename=picture)}}" width="280px" height="150px">
needs tabulation

2019-11-09 17:08 UTC, dimigor commented on flask_advanced/blueprint/Products/utils.py
> +    with open("blueprint/Products/data.json") as file1:
do not hardcode path to file, make this as param and your function will be universal

2019-11-09 17:08 UTC, dimigor commented on flask_advanced/blueprint/Products/utils.py
> +    with open("blueprint/Products/data.json", 'w', encoding='utf-8') as f:
when you write data to file you need to catch some types of error like `file not found`

2019-11-09 17:08 UTC, dimigor commented on flask_advanced/blueprint/Supermarkets/utils.py
> +import json
make one module helper

2019-11-12 22:32 UTC, yuriimchg requested changes
привіт, аппка виглядає дуже круто, також дуже тішить, що є можливість фільтрації відповідей. 
Але є деякі речі, без яких вона буде кращою:


+ довелося трохи поламати імпорти, щоб запустити аппку з консолі
+ можу додати продукт з від'ємною ціною:
![image](https://user-images.githubusercontent.com/33547678/68715725-544b7800-05ab-11ea-9f62-ce26f1e19171.png)
+ також, коли додаю продукт без фото, аппка падає.
+ коли додаю супермаркет без назви і опису, аппка не зупиняє мене і також падає, бо нема ще й фото
+ лінтер трохи свариться на довгі рядки, порожні рядки ітд
+++ зауваження до продуктів стосуються також супермаркетів (ну й навпаки)

2019-11-12 22:32 UTC, yuriimchg commented on flask_advanced/app.py
> +@app.route('/home')
```suggestion
@app.route('/')
@app.route('/home')
```

2019-11-12 22:32 UTC, yuriimchg commented on flask_advanced/blueprint/Products/product.py
> +    for i in get_data(path_data_products):
`i` бажано використовувати, коли змінна, по якій відбувається ітерація, є цілочисельною. Якщо ні, краще назвати її більш інформативно
https://medium.com/better-programming/zen-naming-convention-5314aa0ab67a

2019-11-12 22:32 UTC, yuriimchg commented on flask_advanced/blueprint/Products/product.py
> +        return redirect(url_for('product.get_products'))
це було б дуже класно замінити одним словником

2019-11-12 22:32 UTC, yuriimchg commented on flask_advanced/blueprint/Products/product.py
> +    path = os.path.join('blueprint/Products/static1', image.filename)
шлях бажано винести десь в конфіги чи зразу після імпортів

2019-11-12 22:32 UTC, yuriimchg commented on flask_advanced/blueprint/Products/templates/base.html
> +</html>
no newline at the end of file

2019-11-12 22:32 UTC, yuriimchg commented on flask_advanced/blueprint/Supermarkets/data.json
> +]
newline

2019-11-15 12:54 UTC, dimigor commented on flask_advanced/blueprint/Products/product.py
> +path_data_products = "blueprint/Products/data.json"
if this variable is static and you never change it, name this as a constant like `I_AM_CONSTANT`

2019-11-15 12:54 UTC, dimigor commented on flask_advanced/blueprint/Products/product.py
> +DB1 = get_data(path_data_products)
I think this variable is not a constant, so name it right

2019-11-15 12:54 UTC, dimigor commented on flask_advanced/blueprint/Products/templates/add_product.html
> +		<li class="nav-item">
bad tabulation(

2019-11-15 12:54 UTC, dimigor commented on flask_advanced/blueprint/Supermarkets/supermarket.py
> +@supermarket.route('/s/<name_supermarket>', methods=['GET'])
what is `s`?

2019-11-15 12:54 UTC, dimigor commented on flask_advanced/blueprint/Supermarkets/templates/add_supermarket.html
> +<!--<form method="post" enctype="multipart/form-data">-->
do not comment the code, remove it

2019-11-16 12:50 UTC, dimigor approved these changes
Looks nice!

2019-11-16 12:50 UTC, dimigor commented on flask_advanced/blueprint/Supermarkets/templates/supermarket.html
> +<li class="nav-item">
do not forget about tabulations

2019-11-16 13:41 UTC, merged